In [29]:
import glob
import pandas as pd

In [30]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [31]:
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv_19.csv", index=False, encoding='utf-8-sig')

In [32]:
combined_csv

,Date_time,bg_id,p,q,d,Test_vals,Predicted_vals,mse
0,29/02/2020 03:36:28,data_bg_10420,1,2,1,0.70,[0.27327706],0.210086
1,29/02/2020 04:51:18,data_bg_10420,1,2,1,0.65,[0.62398251],0.210086
2,29/02/2020 12:23:53,data_bg_10420,1,2,1,0.85,[0.53313696],0.210086
3,29/02/2020 13:23:58,data_bg_10420,1,2,1,0.30,[0.71047438],0.210086
4,29/02/2020 13:24:08,data_bg_10420,1,2,1,0.20,[0.3114932],0.210086
5,29/02/2020 13:24:14,data_bg_10420,1,2,1,0.25,[0.29486871],0.210086
6,29/02/2020 19:33:08,data_bg_10420,1,2,1,1.20,[0.31453402],0.210086
7,29/02/2020 19:33:18,data_bg_10420,1,2,1,1.40,[0.9484661],0.210086
8,29/02/2020 20:26:46,data_bg_10420,1,2,1,1.45,[1.03217288],0.210086
9,29/02/2020 23:11:41,data_bg_10420,1,2,1,0.20,[1.15470882],0.210086
10,29/02/2020 23:11:42,data_bg_10420,1,2,1,0.15,[0.2324754],0.210086
11,29/02/2020 23:11:51,data_bg_10420,1,2,1,0.25,[0.3707562],0.210086
12,29/02/2020 23:11:52,data_bg_10420,1,2,1,0.20,[0.37975142],0.210086
13,29/02/2020 23:11:59,data_bg_10420,1,2,1,0.25,[0.32629516],0.210086
14,29/02/2020 23:53:21,data_bg_10420,1,2,1,1.10,[0.35724714],0.210086
0,29/02/2020 02:49:29,data_bg_10429,1,1,0,0.75,[0.8332601],0.092252
1,29/02/2020 03:13:24,data_bg_10429,1,1,0,0.20,[0.72572279],0.092252
2,29/02/2020 03:13:25,data_bg_10429,1,1,0,0.15,[0.45151453],0.092252
3,29/02/2020 03:36:10,data_bg_10429,1,1,0,0.85,[0.58604034],0.092252
4,29/02/2020 03:36:20,data_bg_10429,1,1,0,0.75,[0.93314036],0.092252
5,29/02/2020 04:51:01,data_bg_10429,1,1,0,0.70,[0.64594003],0.092252
6,29/02/2020 04:51:11,data_bg_10429,1,1,0,0.75,[0.80257884],0.092252
7,29/02/2020 10:02:08,data_bg_10429,1,1,0,0.75,[0.73100033],0.092252
8,29/02/2020 10:02:09,data_bg_10429,1,1,0,0.55,[0.77724919],0.092252
9,29/02/2020 10:02:18,data_bg_10429,1,1,0,0.65,[0.62222086],0.092252
10,29/02/2020 10:02:19,data_bg_10429,1,1,0,1.20,[0.78211286],0.092252
11,29/02/2020 11:03:02,data_bg_10429,1,1,0,1.35,[1.01966523],0.092252
12,29/02/2020 11:03:12,data_bg_10429,1,1,0,1.40,[0.96827667],0.092252
13,29/02/2020 12:08:12,data_bg_10429,1,1,0,0.95,[1.05004345],0.092252
14,29/02/2020 12:23:37,data_bg_10429,1,1,0,0.80,[0.71512172],0.092252
...,...,...,...,...,...,...,...,...
211,29/02/2020 20:27:07,data_bg_9896,2,2,0,0.85,[0.93420803],0.019780
212,29/02/2020 20:27:08,data_bg_9896,2,2,0,0.80,[0.91009815],0.019780
213,29/02/2020 20:27:15,data_bg_9896,2,2,0,0.85,[0.88398266],0.019780
214,29/02/2020 20:27:25,data_bg_9896,2,2,0,0.90,[0.89193426],0.019780
215,29/02/2020 20:27:34,data_bg_9896,2,2,0,0.85,[0.91159666],0.019780
216,29/02/2020 20:27:35,data_bg_9896,2,2,0,1.10,[0.89974299],0.019780
217,29/02/2020 20:27:45,data_bg_9896,2,2,0,0.85,[0.9892904],0.019780
218,29/02/2020 20:27:54,data_bg_9896,2,2,0,0.80,[0.93109424],0.019780
219,29/02/2020 20:27:55,data_bg_9896,2,2,0,0.90,[0.89526057],0.019780
220,29/02/2020 21:03:00,data_bg_9896,2,2,0,1.20,[0.91815204],0.019780
221,29/02/2020 21:21:18,data_bg_9896,2,2,0,1.00,[1.03643687],0.019780
222,29/02/2020 21:21:19,data_bg_9896,2,2,0,0.95,[1.00808415],0.019780
0,27/02/2020 10:07:08,data_bg_999,1,1,0,0.85,[1.19337142],0.088573
1,27/02/2020 20:49:43,data_bg_999,1,1,0,0.50,[1.0675748],0.088573
2,27/02/2020 20:49:44,data_bg_999,1,1,0,0.45,[0.86736802],0.088573
3,27/02/2020 20:49:54,data_bg_999,1,1,0,0.65,[0.74726787],0.088573
4,27/02/2020 20:50:03,data_bg_999,1,1,0,0.45,[0.79499648],0.088573
5,27/02/2020 20:50:04,data_bg_999,1,1,0,0.40,[0.70166682],0.088573
6,28/02/2020 00:40:09,data_bg_999,1,1,0,0.20,[0.63041816],0.088573
7,28/02/2020 00:40:19,data_bg_999,1,1,0,0.75,[0.48314037],0.088573
8,28/02/2020 00:40:20,data_bg_999,1,1,0,0.70,[0.70693046],0.088573
9,28/02/2020 00:40:21,data_bg_999,1,1,0,0.75,[0.75818947],0.088573
10,28/02/2020 00:40:29,data_bg_999,1,1,0,0.80,[0.79852042],0.088573
11,28/02/2020 00:40:30,data_bg_999,1,1,0,0.60,[0.83524826],0.088573
12,28/02/2020 00:40:39,data_bg_999,1,1,0,0.70,[0.75799345],0.088573
13,28/02/2020 00:40:40,data_bg_999,1,1,0,1.25,[0.77036482],0.088573
14,28/02/2020 01:27:56,data_bg_999,1,1,0,1.40,[1.01922099],0.088573
15,28/02/2020 01:27:57,data_bg_999,1,1,0,1.35,[1.1947848],0.088573
16,28/02/2020 04:18:17,data_bg_999,1,1,0,1.25,[1.22519922],0.088573
17,28/02/2020 12:28:50,data_bg_999,1,1,0,1.40,[1.18661136],0.088573